Introduce ModelStorageManager and DatasetStorageManager
georgianpartners/annotation_tool pull request #141
Opened 2020-09-28 16:16 UTC by edu-gp

A lot of indirection and duplicate code exist to handle moving _model data_ and _raw datasets_ to and from GCS. In this change, we introduce `ModelStorageManager` and `DatasetStorageManager` under `storage_manager.py` to handle the movement of data. Each StorageManager has conceptually a "local" directory (either on the server, or on the AI Platform), and a "remote" directory (on GCS). They expose interfaces like "download" and "upload". Elsewhere -- in submitting a new AI Platform job, and in starting training within an AI Platform job -- we can use these StorageManagers to simplify a lot of the code.

This also introduces some changes that renames `fname` to either `dataset` or `path`, where appropriate. The definition of a `dataset` is the filename with `.jsonl` ending, e.g. `data.jsonl`. A `path` is the file path, e.g. `/home/user/data.jsonl`. In the codebase, `fname` is loosely defined and sometimes can be either a `dataset` or a `path`, and is a source of confusion and unnecessary code. This PR addresses some of the cases where it's relevant, but not all.

TODO:
- [ ] Fix tests
- [ ] Run a manual test

2020-09-28 18:32 UTC, jzhang-gp requested changes

2020-09-28 18:32 UTC, jzhang-gp commented on train/no_deps/storage_manager.py
> +        self.local_dir = local_model_dir
The comments here don't seem to match with the arguments.

2020-09-28 18:32 UTC, jzhang-gp commented on train/no_deps/gcp_run.py
> +                              inference_cache=inference_cache)
We are building a cache per inference file. Would it make sense to build a cache for all inference files first?

2020-09-28 18:32 UTC, jzhang-gp commented on train/no_deps/storage_manager.py
> +    remote counterpart on GCS."""
Can we also add some contexts on what's in the model's asset?

2020-09-28 18:32 UTC, jzhang-gp commented on train/no_deps/run.py
>      inference_results = InferenceResults(raw)
Is there a python file for the `InferenceResults` class?

2020-09-28 18:35 UTC, edu-gp commented on tests/unit/test_train_no_deps_paths.py
> +    fnames = _inference_fnames_to_datasets([
This function converts an input like `/home/dir/ok.pred.npy` or `ok.pred.npy' to the corresponding dataset `ok.jsonl`. What do you think is a good name for it?

2020-09-28 18:37 UTC, edu-gp commented on train/no_deps/storage_manager.py
> +        self.local_dir = local_model_dir
Fixed

2020-09-28 18:41 UTC, edu-gp commented on train/no_deps/gcp_run.py
> +                              inference_cache=inference_cache)
It does build inference for all files it has already ran inference on. Is that what you meant?

Let's say the model has already ran inference on "a.jsonl" and "b.jsonl" on previous runs, and now we want it to run on "c.jsonl" and "d.jsonl". So, the `infer_fnames` would be `["c.jsonl", "d.jsonl"]`.

Upon the first loop, `dataset = "c.jsonl"`, because `inference_cache` is None, we call `build_inference_cache`, which builds a cache with the previously inferenced results "a.jsonl" and "b.jsonl". Then, when we call `inference(...)`, the `inference_cache` now holds the results from "a.jsonl", "b.jsonl", and "c.jsonl".

On the second loop, `dataset = "d.jsonl"`, and we skip to call `inference(...)` right away because an `inference_cache` already exists.

2020-09-28 18:57 UTC, edu-gp commented on train/no_deps/storage_manager.py
> +    remote counterpart on GCS."""
This isn't quite the right place to do it, so I left a note to point it to `paths.py`, where I added more info.

2020-09-28 18:58 UTC, edu-gp commented on train/no_deps/run.py
>      inference_results = InferenceResults(raw)
https://github.com/georgianpartners/annotation_tool/blob/master/train/no_deps/inference_results.py

2020-09-29 15:06 UTC, jzhang-gp commented on train/no_deps/gcp_run.py
> +                              inference_cache=inference_cache)
OK got it. So `a.jsonl` and `b.jsonl` are already inside the `local_dir` when building the cache.

2020-09-29 15:06 UTC, jzhang-gp commented on tests/unit/test_train_no_deps_paths.py
> +    fnames = _inference_fnames_to_datasets([
Oh I mean on line 7, from `fnames` to `datasets`.

2020-09-29 15:13 UTC, jzhang-gp approved these changes
LGTM

2020-09-29 16:00 UTC, edu-gp commented on train/no_deps/gcp_run.py
> +                              inference_cache=inference_cache)
Yep. In the actual function `build_inference_cache`, it would check if `a.jsonl` and `b.jsonl` exists locally, and download them from GCS as needed.

2020-09-29 16:01 UTC, edu-gp commented on tests/unit/test_train_no_deps_paths.py
> +    fnames = _inference_fnames_to_datasets([
Ah ok. Fixed.

2020-09-29 16:02 UTC, merged