Prevent duplicate labels during task update.
georgianpartners/annotation_tool pull request #182
Opened 2020-11-17 17:02 UTC by jzhang-gp

This is a follow up PR for preventing duplicate labels in Alchemy tasks. The user can update the tasks with a new set of labels and we need to make sure no duplicate labels are included, just like what we did when creating a new task.

The `TaskUpdateRequest` Object is pretty much the same as the `TaskCreateRequest` Object. This is because the update requests only come from a form on the website so all the fields are included when submitting. We could make it more flexible to accept partial fields to update, but it makes the validation process more complicated. Given the current usecase, I would postpone that unless there are new usecases showing up.

There are legacy code to be refactored (for example, `_remove_obsolete_requests_under_task`) so I put TODO there. It's out of scope for this bug fix.

2020-11-17 21:05 UTC, MJafarMashhadi requested changes

2020-11-17 21:05 UTC, MJafarMashhadi commented on tests/unit/dao/test_task_dao.py
> +        )
This will pass if the exception is not raised, should be changed to something like:
```python
expected_message = f"Label {labels[0]} is already created in task {existing_task.name}" 
with pytest.raises(ValueError) as e:
    _ = task_dao.create_task(create_request=create_request)
assert expected_message in str(e.value)
```
or:
```python
expected_message = f"Label {labels[0]} is already created in task {existing_task.name}" 
with pytest.raises(ValueError, match=f'.*{expected_message}.*'):
    _ = task_dao.create_task(create_request=create_request)
```

2020-11-26 19:32 UTC, jzhang-gp commented on alchemy/data/request/task_request.py
> +    id: int
Done.

2020-11-26 19:34 UTC, jzhang-gp commented on tests/unit/dao/test_task_dao.py
> +data_files_updated = data_files.copy() + ["file3.txt"]
Done.

2020-11-26 19:34 UTC, jzhang-gp commented on tests/unit/dao/test_task_dao.py
> +@pytest.mark.parametrize("new_labels", [labels_updated, labels.copy() + ["new_label"]])
Done.

2020-11-26 19:35 UTC, jzhang-gp commented on tests/unit/dao/test_task_dao.py
> +        labels=labels.copy() + ["new_label"],
Done.

2020-11-26 19:37 UTC, jzhang-gp commented on tests/unit/dao/test_task_dao.py
> +        )
True. Updated :)

2020-11-26 21:05 UTC, MJafarMashhadi approved these changes

2020-11-26 21:05 UTC, MJafarMashhadi commented
All good to me!

2020-11-26 21:33 UTC, merged