Filter empty text from training data.
georgianpartners/annotation_tool pull request #197
Opened 2021-01-05 19:11 UTC by jzhang-gp

We want to filter out annotations with empty text in the descriptions.

2021-01-05 20:34 UTC, MJafarMashhadi approved these changes

2021-01-05 20:34 UTC, MJafarMashhadi commented on alchemy/db/model.py
> +            if looked_up_text == "":
I would prefer to use `if not looked_up_text or not looked_up_text.strip():` since it handles None and "    " too.

2021-01-05 20:34 UTC, MJafarMashhadi commented on tests/unit/test_classification_training_data.py
> +    monkeypatch.setenv("ALCHEMY_FILESTORE_DIR", str(tmp_path))
Note to self to update #174

2021-01-06 20:07 UTC, jzhang-gp commented on alchemy/db/model.py
> +            if looked_up_text == "":
Done.

2021-01-06 21:01 UTC, MJafarMashhadi requested changes

2021-01-07 14:46 UTC, jzhang-gp commented on alchemy/scripts/train_with_custom_data_new.py
> +    assert docker_image_uri
Separate issue. I'll move to a different PR.

2021-01-07 14:47 UTC, jzhang-gp commented on alchemy/scripts/train_with_custom_data_new.py
> +    if docker_image_uri is None:
Same as above. I'll move it to a different PR.

2021-01-07 14:53 UTC, jzhang-gp commented on alchemy/scripts/train_with_custom_data_new.py
> +        f"gcloud ai-platform jobs submit training {job_id}" f" --config {config_file}"
Same as above. I'll add to a separate task and PR.

2021-01-07 14:56 UTC, jzhang-gp commented
@MJafarMashhadi I created 3 separate tasks based on your comment. For this particular change, it is only about removing empty text so let's make it contained :)

2021-01-07 14:57 UTC, MJafarMashhadi approved these changes

2021-01-07 15:01 UTC, MJafarMashhadi commented
> @MJafarMashhadi I created 3 separate tasks based on your comment. For this particular change, it is only about removing empty text so let's make it contained :)

Right, I was wondering why that file was here too

2021-01-14 21:05 UTC, merged