AUPR changes in the training script
georgianpartners/annotation_tool pull request #198
Opened 2021-01-06 20:04 UTC by jzhang-gp

Change the metric calculation to AUPR based on the discussion on Slack

2021-01-06 20:51 UTC, MJafarMashhadi approved these changes

2021-01-06 20:51 UTC, MJafarMashhadi commented on alchemy/train/no_deps/metrics.py
> +    average_precision_score,
Maybe we can have a dynamic way to add/remove/update the metrics as a future feature. sklearn has already done much of the heavy lifting on our behalf, i.e. creating a unified interface for all the metrics, we just need to do some basic `importlib` magic to load the metrics dynamically and apply them on the data.

2021-01-07 01:21 UTC, angeliney commented
@jzhang-gp can we add the AUPR and still keep the previous ROC AUC?

2021-01-07 19:51 UTC, angeliney requested changes
As mentioned in an earlier comment, let's keep the original roc_auc_score but add the average_precision_score on top :) Is that possible?

2021-01-07 19:59 UTC, jzhang-gp commented
> @jzhang-gp can we add the AUPR and still keep the previous ROC AUC?

You mean add it as a separate metric? 

> @jzhang-gp can we add the AUPR and still keep the previous ROC AUC?



> As mentioned in an earlier comment, let's keep the original roc_auc_score but add the average_precision_score on top :) Is that possible?

Sure. We can do that.

2021-01-07 20:33 UTC, jzhang-gp commented
<img width="786" alt="image" src="https://user-images.githubusercontent.com/45179326/103941937-9879d000-50fd-11eb-9385-82044bb78bf4.png">
@angeliney does this look OK to you?

2021-01-07 23:22 UTC, angeliney approved these changes
Looks good!!

2021-01-13 16:18 UTC, merged